### ISSUE TITLE
change structure so that CoTeTo can be used as a submodule in other git repositories

### ISSUE THREAD

**Issue by thorade** [UdK-VPT/CoTeTo#3]
As discussed previously:
It would be nice to define one (additional) default path where CoTeTo is looking for Generators.
That path could be e.g. a directory named CoTeTo_Generators, placed next to CoTeTo.
That would allow us to have a private git repository that uses CoTeTo as submodule and only adds new generators.

Currently, we have several copies of CoTeTo in various repositories.

**Comment by thorade** [comment]
@jraedler Is this also done in PR #6 ?
If yes, this issue should be closed and it would be good to have one example usage of the feature.

**Comment by jraedler** [comment]
Yes, this is implemented and tested. If a folder CoTeTo_Generators next to the CoTeTo main folder exists, it will be added to the generator search path. But I don't know how to include an example for this in CoTeTo, because it would need to reference a folder outside the CoTeTo folder structure.

**Comment by thorade** [comment]
There are now at least three examples of how to use CoTeTo as a submodule.

**Comment by thorade** [comment]
There are now three examples, but I am not yet sure how to add additional "Loaders" when using CoTeTo as submodule, I keep getting
```
  File "C:\Users\mthorade\Anaconda3\lib\configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'LOADER'
```

Update: Generators can bring a specific loader (just add a subdirectory Loaders to the generator). But can I also use a directory `CoTeTo_Loaders` and use one loader in multiple generators?

Similar discussion for filters. Or maybe move longer Python code from a filter to the loader instead?

Loaders are often just a few lines, filters can be very many lines, and it should be possible to share the filter code between generators.

**Comment by thorade** [comment]
Closing for now.
Currently, loaders and filters have to be part of a generator.
